name: Upload Only Updated SQL Scripts to Azure Blob

on:
  push:
    branches:
      - main
    paths:
      - 'scripts/**/*.sql'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Delete all files in the container (truncate)
      run: |
        echo "Deleting existing .sql files in the container..."
        az storage blob delete-batch \
          --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
          --source ${{ secrets.AZURE_CONTAINER_NAME }} \
          --pattern *.sql \
          --auth-mode login || true

    - name: Debug commit SHAs
      run: |
        echo "From: ${{ github.event.before }}"
        echo "To:   ${{ github.sha }}"

    - name: Upload only updated SQL files
      run: |
        prev_commit=$(git rev-parse HEAD~1)
        curr_commit=$(git rev-parse HEAD)

        echo "Diffing from $prev_commit to $curr_commit"

        changed_files=$(git diff --name-only "$prev_commit" "$curr_commit" | grep '^scripts/.*\.sql$')

        echo "Changed SQL files:"
        echo "$changed_files"

        # Upload each changed file
        for file in $changed_files; do
          echo "Uploading $file..."
          az storage blob upload \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --container-name ${{ secrets.AZURE_CONTAINER_NAME }} \
            --name "${file#scripts/}" \
            --file "$file" \
            --overwrite \
            --auth-mode login
        done
